version: "3.9"

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "root"

    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    build: .
    ports:
      - "8000:8000"
    links:
      - db:db
      - redis:redis

    volumes:
      - type: bind
        source: .
        target: /app

    env_file: .env
    command: bash -c "python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py collectstatic --no-input &&
      python3 manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: madefire/chordtest
    command: bash -c "celery -A todo worker -l INFO"
    environment:
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
    volumes:
      - ./:/app/
    depends_on:
      - redis

volumes:
  media:
  pgdata:
